import React from 'react';
import { LegalLayout } from '../components/LegalLayout';

const Privacy: React.FC = () => (
  <LegalLayout title="Privacy Policy" activePage="privacy" lastUpdated="22 August 2026">
    <div className="space-y-10 text-brand-black font-light leading-relaxed text-sm md:text-base">
      <section className="space-y-3"><h3 className="text-xl font-bold">1. Introduction</h3><p>At Rivo, we value your privacy and are committed to protecting personal information. This Privacy Policy explains how we collect, use, store, share, and safeguard data when you use our website, mobile applications, and hyperlocal marketplace services.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">2. Information We Collect</h3><p>Depending on the service you use, we may collect:</p><ul className="list-disc pl-5 space-y-2 text-brand-gray-muted font-normal"><li>Name, email address, mobile number, and account information.</li><li>Delivery addresses and drop-off instructions.</li><li>Profile information and order history.</li><li>Payment and transaction information needed to process orders; sensitive payment credentials are handled by payment providers.</li><li>Device information, diagnostics, browser/app information, and technical logs.</li><li>Location information where required for local discovery, addresses, routing, or delivery operations.</li><li>Support communications, messages, and related records.</li></ul></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">3. How We Use Information</h3><p>We use information to create and manage accounts, process orders and transactions, coordinate vendors and riders, provide support, send service notifications, improve the platform, prevent fraud and unauthorized access, and comply with applicable law.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">4. Location Information</h3><p>Rivo may use location information to show nearby businesses, associate addresses with orders, calculate delivery distances, support delivery operations, and improve local services. Permissions can be managed through your device settings.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">5. Cookies & Similar Technologies</h3><p>Our website may use cookies or similar technologies for preferences, security, analytics, and website functionality. Browser settings may allow you to control cookies, although some features may be affected.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">6. Information Sharing</h3><p>We do not sell personal information. Information may be shared when necessary with vendors for order fulfilment, riders for delivery, payment providers for transactions, service providers supporting infrastructure, and authorities where required by law.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">7. Data Security</h3><p>We use reasonable technical and organizational safeguards designed to protect personal information against unauthorized access, loss, alteration, or misuse. No online system can be guaranteed completely secure.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">8. Data Retention</h3><p>We retain information for as long as reasonably necessary to provide services, complete transactions, resolve disputes, meet business obligations, and comply with legal or tax requirements. Information that is no longer required may be deleted or anonymized, subject to applicable retention obligations.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">9. User Rights</h3><p>Subject to applicable law, you may request access to or correction of personal information and request account or data deletion. Some information may need to be retained for legal, security, fraud-prevention, transaction, or dispute-resolution purposes.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">10. Children's Privacy</h3><p>Rivo is not intended for children below the applicable legal age. We do not knowingly collect personal information from children where prohibited by law.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">11. Third-Party Services</h3><p>Rivo may use or link to third-party services such as payment, hosting, analytics, mapping, authentication, and communication providers. Those providers may have their own terms and privacy policies.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">12. Policy Updates</h3><p>We may update this Privacy Policy as the platform, services, or applicable requirements change. The Last Updated date will be revised when material updates are published.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">13. Contact</h3><p>For privacy questions, complaints, or requests, contact Rivo Support:</p><p className="font-bold text-brand-black bg-[#FAF9FA] border border-neutral-200 rounded-xl p-4 inline-block tracking-tight select-all">support@rivocity.com</p></section>
    </div>
  </LegalLayout>
);

export default Privacy;
