import React from 'react';
import { LegalLayout } from '../components/LegalLayout';

const Terms: React.FC = () => (
  <LegalLayout title="Terms & Conditions" activePage="terms" lastUpdated="22 August 2026">
    <div className="space-y-10 text-brand-black font-light leading-relaxed text-sm md:text-base">
      <section className="space-y-3"><h3 className="text-xl font-bold">1. Introduction</h3><p>Welcome to Rivo. These Terms & Conditions govern your access to and use of Rivo’s website, mobile applications, and connected services. By using our platform, you agree to follow these rules. If you do not agree with any part of these terms, please do not use our services.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">2. Acceptance of Terms</h3><p>By accessing or browsing our platform, downloading the app, placing an order, or registering a store or rider account, you acknowledge that you have read, understood, and agreed to be bound by this document. These terms form a binding legal agreement between you and Rivo.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">3. Eligibility</h3><p>To use Rivo, you must be at least 18 years old and fully capable of entering into legally binding contracts under applicable Indian law. If you are registering an account on behalf of a business entity, you represent that you have the authority to bind that entity to these terms.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">4. Account Registration</h3><p>You agree to provide accurate, current, and complete information during registration and to keep it updated. You are responsible for maintaining the security of your account credentials and for activities and orders occurring under your account.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">5. Platform Services</h3><p>Rivo operates as a technology platform providing an online hyperlocal marketplace that connects local customers with local retail businesses (vendors) and delivery partners (riders).</p><p>Rivo does not own, manufacture, sell, or store the products listed by vendors and does not directly employ riders. Vendor product sales and delivery fulfilment are performed by the relevant participating parties through the platform.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">6. Orders</h3><p>An order placed on the platform represents a customer request to purchase a product from a vendor. Acceptance occurs when the vendor confirms the order. Orders remain subject to product availability.</p><p>Customer cancellation availability depends on the order stage and the applicable Refund & Cancellation Policy. Delivery estimates are approximations and are not guaranteed arrival deadlines.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">7. Payments</h3><p>Rivo may support digital payment methods and Cash on Delivery where enabled for the relevant order or city. Available payment methods are shown during checkout.</p><p>Product prices are determined by vendors. Applicable taxes and delivery charges, where applicable, are displayed before order confirmation.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">8. Vendor Responsibilities</h3><p>Vendors are responsible for the accuracy of their listings, pricing, inventory, product quality, packaging, licences, and compliance with applicable laws and regulations.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">9. Rider Responsibilities</h3><p>Riders agree to conduct deliveries safely and professionally, comply with traffic and transport requirements, protect customer information, and follow Rivo operational instructions.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">10. User Responsibilities</h3><p>Customers, vendors, and riders must provide truthful information, use Rivo only for lawful purposes, behave respectfully, and avoid conduct that could harm other users or the platform.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">11. Prohibited Activities</h3><p>Fraud, fake or malicious orders, abuse, spam, unauthorized access, security bypasses, reverse engineering, and unlawful use of the platform are prohibited.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">12. Intellectual Property</h3><p>The Rivo name, logos, website, applications, text, graphics, software, and other proprietary materials are protected intellectual property. They may not be copied or redistributed without authorization.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">13. Privacy</h3><p>Your use of Rivo is also governed by our Privacy Policy, which explains how personal information is collected, used, shared, retained, and protected.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">14. Limitation of Liability</h3><p>To the maximum extent permitted by applicable law, Rivo is not liable for indirect, incidental, special, or consequential losses arising from use of the platform, including vendor product issues, delivery delays, or disputes between participating parties.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">15. Force Majeure</h3><p>Rivo is not responsible for interruptions or delays caused by circumstances beyond reasonable control, including severe weather, natural disasters, infrastructure outages, civil disruptions, or government restrictions.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">16. Termination</h3><p>Rivo may suspend or terminate access where necessary for security, fraud prevention, legal compliance, serious policy violations, or protection of the platform and its users.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">17. Changes to Terms</h3><p>We may update these Terms & Conditions as the platform or applicable requirements change. The Last Updated date will be revised when material updates are published.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">18. Governing Law</h3><p>These Terms & Conditions are governed by the laws of India. Disputes are subject to the jurisdiction of competent courts in Maharashtra, India, subject to applicable law.</p></section>
      <section className="space-y-3"><h3 className="text-xl font-bold">19. Contact</h3><p>For questions or clarification regarding these Terms & Conditions, contact Rivo Support:</p><p className="font-bold text-brand-black bg-[#FAF9FA] border border-neutral-200 rounded-xl p-4 inline-block tracking-tight select-all">support@rivocity.com</p></section>
    </div>
  </LegalLayout>
);

export default Terms;
